######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 10 14:49:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += analogclock.h
SOURCES += analogclock.cpp main.cpp
