#! /bin/sh
set -x
gst-launch filesrc location=/usr/share/esc-media/sprc720.flv ! flvdemux name=demux demux.audio ! queue  max-size-buffers=8000 max-size-time=0 max-size-bytes=0 ! mad ! alsasink demux.video ! queue ! ffdec_vp6f ! dmaiperf print-arm-load=true ! omapdmaifbsink

