#! /bin/sh
PATTERN=0
if [ -n "$1" ] ; then
   PATTERN=$1
fi
set -x
./autogain/autogain
gst-launch-1.0 v4l2src ! 'video/x-raw,width=320,height=240,framerate=30/1' ! \
tee name=t_vid ! queue ! xvimagesink sync=false t_vid. ! queue ! videorate ! \
'video/x-raw,framerate=30/1' ! theoraenc ! queue ! oggmux ! \
filesink location=test.ogg

# From http://www.twm-kd.com/linux/webcam-and-linux-gstreamer-tutorial/
