######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 9 13:52:38 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
