#! /bin/sh
BUFFER=700

if [ -n "$1" ] ; then
   BUFFER=$1
fi

set -x
gst-launch filesrc location=esc-media/AlphaAnimal.m4a num-buffers=$BUFFER ! qtdemux ! TIAuddec1 codecName=aachedec engineName=codecServer ! alsasink

