#!/bin/bash
# Test for the big screen
if xwininfo -root | grep -q 3840x2160; then
	gnome-terminal --geometry=120x24+850-20
	gnome-terminal --geometry=80x24+90-12
	gnome-terminal --geometry=80x60+92+525
	gnome-system-monitor --geometry=790x600-26+4 &
fi
