syntax on
:set number

"From: https://www.cloudsavvyit.com/9884/define-a-great-vim-profile-using-vimrc/
set nocompatible
colo torte
syntax on
set tabstop     =2
set softtabstop =2
set shiftwidth  =2
" set expandtab

